baseURL: "https://yukun-guo.github.io/mywebsite/public"
languageCode: en-us
title: Yukun Guo
theme: personal-web
copyright: © Yukun Guo
googleAnalytics: ''
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
params:
  accentColor: '#FD3519'
  assets:
    customCSS: ''
    favicon: ''
  breadcrumb: yes
  contact:
    email: 'guoyukn@gmail.com'
  #  text: ''
  intro:
    main: 'Hi, I''m Yukun :wave:'
    sub: I'm a PhD Candidate at Oregon Health & Science University
  main:
    latestPublishHeader:
  mainSections: portfolio
  notFound:
    gopher: /images/gopher.png
    h1: Bummer!
    p: It seems that this page doesn't exist.
  sections:
    portfolio: project
    post: article
  sidebar:
    backgroundImage: ''
    gradientOverlay: ''
    logo: '/images/yukun-guo.jpg'
  social:
#    codepen: https://codepen.io/
#    facebook: https://www.facebook.com/
    github: https://github.com/Yukun-Guo/
    googlescholar: https://scholar.google.com/citations?user=BCrQPWUAAAAJ&hl=en/
#    gitlab: https://gitlab.com/
#    instagram: https://www.instagram.com/
#    keybase: https://keybase.io/
#    linkedin: https://www.linkedin.com/in/
#    medium: https://medium.com/
#    twitter: https://twitter.com/
#    youtube: https://www.youtube.com/
taxonomies:
  design: designs
  tech: techs
blackfriday:
  hrefTargetBlank: yes
menu:
  main:
    - identifier: about
      name: About
      title: About section
      url: /about/
      weight: -120
    - identifier: portfolio
      name: Portfolio
      title: Portfolio
      #url: /portfolio/
      weight: -110
    - identifier: blog
      name: Post
      title: Blog section
      #url: /post/
      weight: -100
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
privacy:
  googleAnalytics:
    anonymizeIP: yes
    disable: yes
    respectDoNotTrack: yes
    useSessionStorage: no
  twitter:
    disable: no
    enableDNT: yes
    simple: no
markup:
  goldmark:
    renderer:
      unsafe: yes
